{% set name = "featurewiz" %}
{% set version = "0.5.83" %}
{% set python_min = python_min|default("3.7") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/featurewiz-{{ version }}.tar.gz
  sha256: 980d37bcb8b58d8f8333d6708f899a8edf736b329bcc8d13e4d778d09dd046fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy <2.0
    - ipython
    - jupyter
    - xgboost >=1.6.2,<=1.7.6
    - pandas >=2.0
    - matplotlib-base
    - seaborn
    - scikit-learn >=1.2.2,<=1.5.2
    - networkx
    - category_encoders =2.6.3
    - xlrd >=2.0.0
    - tqdm >=4.61.1
    - dask-core >=2021.11.0
    - lightgbm >=3.2.1
    - distributed >=2021.11.0
    - feather-format >=0.4.1
    - pyarrow >=7.0.0
    - fsspec >=0.3.3
    - scipy
    - pillow >=9.0.0
    - numexpr >=2.7.3
    - tensorflow >=2.5.2
    - lazytransform

test:
  requires:
    - python ={{ python_min }}
    - pip
  imports:
    - featurewiz
  commands:
    - pip check

about:
  home: https://github.com/AutoViML/featurewiz
  summary: Select Best Features from your data set - any size - now with XGBoost!
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - arturdaraujo
    - mfansler
